### ISSUE TITLE
Push fails for complex directory structure

### ISSUE THREAD

**Issue by Mon-143** [ChristofferNissen/helmper#109]
While trying to push images which has a different directory structure, it doesn't work and helmper throws error :

for eg : while pushing charts for **[aws-ebs-csi-driver_2.32.0](https://artifacthub.io/packages/helm/aws-ebs-csi-driver/aws-ebs-csi-driver/2.32.0)** the associated images like "public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.11.0-eks-1-30-8" where more than one directory resides , in such case image does not get pushed to OCI registry.

```
{"time":"2024-10-08T05:51:03.840155299Z","level":"INFO","msg":"Image not available. will be excluded from import...","image":""}
{"time":"2024-10-08T05:51:04.782997215Z","level":"INFO","msg":"Image not available. will be excluded from import...","image":"public.ecr.aws/eks-distro/kubernetes-csi:v8.0.1-eks-1-30-8"}
{"time":"2024-10-08T05:51:04.785323639Z","level":"INFO","msg":"Image not available. will be excluded from import...","image":"public.ecr.aws/eks-distro/kubernetes-csi:v2.11.0-eks-1-30-8"}
{"time":"2024-10-08T05:51:04.7874143Z","level":"INFO","msg":"Image not available. will be excluded from import...","image":"public.ecr.aws/eks-distro/kubernetes-csi:v5.0.1-eks-1-30-8"}
```

**Comment by ChristofferNissen** [comment]
Thanks for opening an issue. Will investigate and get back shortly
