### ISSUE TITLE
Feature: Retrying failed connections

### ISSUE THREAD

**Issue by tommy-dk** [ChristofferNissen/helmper#30]
Hello!

While running `helmper` it tries to communicate with various sources, services and registries. Sometimes they don't respond in a timely fashion, thus rendering a `context deadline exceeded` error and exiting abruptly halfway through the execution. See example here:

> `{"time":"2024-05-29T12:56:01.142365493Z","level":"ERROR","msg":"signing digest: Head \"https://xyz.azurecr.io/v2/openebs/provisioner-nfs/manifests/sha256-f8a913f70026e86dae967050b6cd3790b81dd7c9c580aab306c3a0f36ca49b18.sig\": context deadline exceeded"}`

It would be very useful to be able to adjust the timeouts through configuration, but also that `helmper` uses an exponential backoff mechanism for retrying the failed connection.

**Comment by ChristofferNissen** [comment]
Ah, this is when running Cosign, I added this logic already for Helm. Thanks for raising this issue, will look into it 🙌
