### ISSUE TITLE
[feat] support images used by Operators

### ISSUE THREAD

**Issue by Pionerd** [ChristofferNissen/helmper#39]
Some operators (e.g. CNPG to create Postgres databases) do not specify the images used by their CustomResources (e.g. `Cluster` in the case of CNPG). In the case of CNPG, the image can be configured in the Cluster CR, but that is not required (see https://cloudnative-pg.io/documentation/1.22/quickstart/#part-3-deploy-a-postgresql-cluster). 

I'd love either: 
- the option to specify in helmper.yaml a list of additional images that should be pulled/processed by helmper manually
- or documentation on adding 'dummy' values to your values.yaml that include the missing images, probably something like the below should work (didn't test this yet):

values.yaml
```
helmperAdditionalImages:
  postgres16
    image: ghcr.io/cloudnative-pg/postgresql:17
  postgres17
    image: ghcr.io/cloudnative-pg/postgresql:17
```

**Comment by ChristofferNissen** [comment]
Hello 👍 

This has been implemented as part of v1.5.0
