### ISSUE TITLE
Feature request: specify architecture

### ISSUE THREAD

**Issue by Pionerd** [ChristofferNissen/helmper#42]
When running helmper on my M2 Mac, it pulls the ARM images. However, on my servers I need the AMD64 images. It would be great if we could specify the architecture of images to import (even if this would limit the usage of other features).

**Comment by ChristofferNissen** [comment]
Hello 👋 this has been released as part of V1.5.0

Let me know if it's working for you, I am not fortunate enough to have any arm hardware at the moment
